baseurl = "http://matas.me/"
title = ""
languageCode = "en-us"
disqusShortname = "algirdasmatas" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "Algirdas Matas"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "About me, my thoughts, projects and anything else I find interesting."
    defaultKeywords = "webpage,blog,running,marathon,golang,go,traveling"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-cc"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = ""

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    #googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "UA-68451667-1"
    #gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/rndz"
    linkedin = "https://lt.linkedin.com/pub/algirdas-matas/103/8a2/bb"
    googleplus = "https://plus.google.com/+AlgirdasMatas"
    facebook = "https://www.facebook.com/algirdas.matas.7"
    twitter = "https://twitter.com/algis_m"

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
